name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you are requesting.
    validations:
      required: false
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature would be useful.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
    validations:
      required: false
