name: Trigger Supabase Cleanup API

on:
  schedule:
    # Run daily at 2 AM UTC (adjust as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  trigger_cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Call Supabase Cleanup Endpoint
      env:
        # The base URL of your deployed backend on Vercel
        VERCEL_BACKEND_URL: ${{ secrets.VERCEL_BACKEND_URL }}
      run: |
        if [ -z "$VERCEL_BACKEND_URL" ]; then
          echo "Error: VERCEL_BACKEND_URL secret is not set."
          exit 1
        fi
        echo "Triggering Supabase cleanup at $VERCEL_BACKEND_URL/api/clean-supabase/trigger"
        curl -X GET "$VERCEL_BACKEND_URL/api/clean-supabase/trigger"